In [42]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

In [2]:
data = pd.read_excel('MealAnalysis.xlsx','data')
data.head(10)

,Type,gender,age,height,weight,EER[kcal],P target(15%)[g],F target(25%)[g],C target(60%)[g],number of dishes,E[kcal],P[g],F[g],C[g],Salt[g],Vegetables[g],Score(1:worst 2:bad 3:good 4:best)
1,breakfast,female,32.0,157.0,48.0,1655,62.043750,45.958333,248.175000,2,333.87,5.85,0.75,75.69,0.21,29.0,2
2,breakfast,female,35.0,161.0,55.0,2073,77.745091,57.588956,310.980364,2,213.85,4.62,4.48,41.25,0.11,0.0,1
3,breakfast,female,26.0,159.0,51.0,2042,76.584375,56.729167,306.337500,4,351.59,27.31,18.85,18.10,2.84,116.4,2
4,breakfast,female,48.0,164.0,57.0,1772,66.431250,49.208333,265.725000,2,295.43,5.63,0.89,65.08,0.65,189.0,2
5,dinner,female,48.0,164.0,57.0,1772,66.431250,49.208333,265.725000,5,876.19,41.46,34.16,96.30,6.37,53.5,2
6,lunch,female,48.0,164.0,57.0,1772,66.431250,49.208333,265.725000,1,424.04,14.52,24.97,34.41,2.28,33.0,2
7,breakfast,female,48.0,164.0,57.0,1772,66.431250,49.208333,265.725000,1,346.63,11.13,8.55,54.02,2.00,6.0,2
8,NaN,NaN,NaN,NaN,NaN,1772,66.431250,49.208333,265.725000,3,238.44,6.14,10.92,31.11,1.60,299.0,3
9,dinner,female,48.0,164.0,57.0,1772,66.431250,49.208333,265.725000,1,563.33,22.50,20.25,67.92,2.17,125.0,2
10,lunch,female,48.0,164.0,57.0,1772,66.431250,49.208333,265.725000,1,266.00,7.50,5.04,47.69,0.67,0.0,1

We can first load data and check it if there's anything happens unexcepted.
Just like the 8th row has null data, then I'll drop it for cleansing.

In [3]:
data1 = data.drop(data[data['Type'].isnull()].index)
data1.head(10)

,Type,gender,age,height,weight,EER[kcal],P target(15%)[g],F target(25%)[g],C target(60%)[g],number of dishes,E[kcal],P[g],F[g],C[g],Salt[g],Vegetables[g],Score(1:worst 2:bad 3:good 4:best)
1,breakfast,female,32.0,157.0,48.0,1655,62.043750,45.958333,248.175000,2,333.87,5.85,0.75,75.69,0.21,29.0,2
2,breakfast,female,35.0,161.0,55.0,2073,77.745091,57.588956,310.980364,2,213.85,4.62,4.48,41.25,0.11,0.0,1
3,breakfast,female,26.0,159.0,51.0,2042,76.584375,56.729167,306.337500,4,351.59,27.31,18.85,18.10,2.84,116.4,2
4,breakfast,female,48.0,164.0,57.0,1772,66.431250,49.208333,265.725000,2,295.43,5.63,0.89,65.08,0.65,189.0,2
5,dinner,female,48.0,164.0,57.0,1772,66.431250,49.208333,265.725000,5,876.19,41.46,34.16,96.30,6.37,53.5,2
6,lunch,female,48.0,164.0,57.0,1772,66.431250,49.208333,265.725000,1,424.04,14.52,24.97,34.41,2.28,33.0,2
7,breakfast,female,48.0,164.0,57.0,1772,66.431250,49.208333,265.725000,1,346.63,11.13,8.55,54.02,2.00,6.0,2
9,dinner,female,48.0,164.0,57.0,1772,66.431250,49.208333,265.725000,1,563.33,22.50,20.25,67.92,2.17,125.0,2
10,lunch,female,48.0,164.0,57.0,1772,66.431250,49.208333,265.725000,1,266.00,7.50,5.04,47.69,0.67,0.0,1
11,breakfast,female,48.0,164.0,57.0,1651,61.912500,45.861111,247.650000,5,691.88,23.03,24.51,97.75,2.37,0.0,2

Then we can simplify the data from gender for 2 subsets, data_male and data_female.

In [29]:
data_male = data1[data1['gender']=='male']
data_female = data1[data1['gender']=='female']

Here I ignore the differences between meal types for simplifying the process, thus we could make more detailed analysis by drilling down the types.
The data range is obviously wider than imagine, so at the first we could give them a normalized process.
We could make data precess on 1 subset first, here I choose the data_male.

From the correlation matrix, we can find that the EER and targets of protein, fat and carbo are highly correlated, thus we only keep the EER here. Besides, the calories E is also highly correlated to Protein, Fat and Carbo. But here I'll pop the E column because the calories are calculated from those nutrients.

In [54]:
df = data_male[data_male.columns[2:-2]]
ndf = (df-df.mean())/df.std()
corr = ndf.corr()
corr

,age,height,weight,EER[kcal],P target(15%)[g],F target(25%)[g],C target(60%)[g],number of dishes,E[kcal],P[g],F[g],C[g],Salt[g]
age,1.000000,-0.359347,0.111133,-0.165772,-0.165824,-0.165824,-0.165824,0.169754,0.011352,-0.057764,0.027012,0.039215,-0.102840
height,-0.359347,1.000000,0.162945,0.029316,0.029361,0.029361,0.029361,-0.031974,-0.010690,0.004533,-0.041922,0.028993,0.045136
weight,0.111133,0.162945,1.000000,0.493211,0.493478,0.493478,0.493478,-0.052112,0.132584,0.084208,0.072927,0.180799,0.052224
EER[kcal],-0.165772,0.029316,0.493211,1.000000,0.999999,0.999999,0.999999,-0.055735,0.086997,0.109103,0.023852,0.106266,0.105603
P target(15%)[g],-0.165824,0.029361,0.493478,0.999999,1.000000,1.000000,1.000000,-0.055747,0.087046,0.109134,0.023921,0.106317,0.105572
F target(25%)[g],-0.165824,0.029361,0.493478,0.999999,1.000000,1.000000,1.000000,-0.055747,0.087046,0.109134,0.023921,0.106317,0.105572
C target(60%)[g],-0.165824,0.029361,0.493478,0.999999,1.000000,1.000000,1.000000,-0.055747,0.087046,0.109134,0.023921,0.106317,0.105572
number of dishes,0.169754,-0.031974,-0.052112,-0.055735,-0.055747,-0.055747,-0.055747,1.000000,0.354231,0.382642,0.313337,0.202324,0.248916
E[kcal],0.011352,-0.010690,0.132584,0.086997,0.087046,0.087046,0.087046,0.354231,1.000000,0.844411,0.823209,0.750545,0.711351
P[g],-0.057764,0.004533,0.084208,0.109103,0.109134,0.109134,0.109134,0.382642,0.844411,1.000000,0.730174,0.537900,0.791269
F[g],0.027012,-0.041922,0.072927,0.023852,0.023921,0.023921,0.023921,0.313337,0.823209,0.730174,1.000000,0.306866,0.563491
C[g],0.039215,0.028993,0.180799,0.106266,0.106317,0.106317,0.106317,0.202324,0.750545,0.537900,0.306866,1.000000,0.555363
Salt[g],-0.102840,0.045136,0.052224,0.105603,0.105572,0.105572,0.105572,0.248916,0.711351,0.791269,0.563491,0.555363,1.000000

In [55]:
ndf.drop(["P target(15%)[g]","F target(25%)[g]","C target(60%)[g]","E[kcal]"],axis = 1, inplace = True)
Score = data_male[data_male.columns[-1]]

As I remove the correlated features and there are only normalized features, I applied a simple linear regression model here to find out the relationship between the features and scores.

We can find the weights of each feature here, which means the age and height are not necessary features here. The Fat is the only negative feature here, which means the more fat, the less score.

In [56]:
linearModel=LinearRegression()
linearModel.fit(ndf,Score)
print(ndf.columns)
print(linearModel.coef_)
print(linearModel.intercept_)

Index(['age', 'height', 'weight', 'EER[kcal]', 'number of dishes', 'P[g]',
       'F[g]', 'C[g]', 'Salt[g]'],
      dtype='object')
[ 0.00802528  0.00822038  0.05080964  0.02151798  0.15075059  0.01017074
 -0.01506128  0.22639173  0.11258324]
1.885467980295567

In [51]:
mse = np.mean((linearModel.predict(ndf) - Score) ** 2)
r_squared = linearModel.score(ndf, Score)
adj_r_squared = r_squared - (1 - r_squared) * (ndf.shape[1] / (ndf.shape[0] - ndf.shape[1] - 1))
print(mse, r_squared, adj_r_squared)

0.2916543512264681 0.33541654177372204 0.3279586226664446

I also evaluate the linear regression model, for MSE, R^2 and adjusted R^2 are all lower than 0.5, this model could be modified more.

In [59]:
df = data_female[data_female.columns[2:-2]]
ndf = (df-df.mean())/df.std()
ndf.drop(["P target(15%)[g]","F target(25%)[g]","C target(60%)[g]","E[kcal]"],axis = 1, inplace = True)
Score = data_female[data_female.columns[-1]]
linearModel=LinearRegression()
linearModel.fit(ndf,Score)
print(ndf.columns)
print(linearModel.coef_)
print(linearModel.intercept_)
mse = np.mean((linearModel.predict(ndf) - Score) ** 2)
r_squared = linearModel.score(ndf, Score)
adj_r_squared = r_squared - (1 - r_squared) * (ndf.shape[1] / (ndf.shape[0] - ndf.shape[1] - 1))
print(mse, r_squared, adj_r_squared)

Index(['age', 'height', 'weight', 'EER[kcal]', 'number of dishes', 'P[g]',
       'F[g]', 'C[g]', 'Salt[g]'],
      dtype='object')
[ 1.06892001e-02 -6.16003272e-03  5.01382594e-02  2.95212919e-04
  2.15665773e-01 -8.02677519e-02 -1.75962935e-02  1.56817610e-01
  3.13005130e-01]
2.093625498007969
0.3864362818620568 0.34594985140761636 0.33398551942117033

From the same analysis applied to female subset, the result is almost the same.